# Generated by Django 3.2 on 2021-04-25 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mapbox_location_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=255, verbose_name='Ссылка на аватар')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Impress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название воспоминания')),
                ('info', models.TextField(null=True, verbose_name='Инофрмация о воспоминании')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
                ('location', mapbox_location_field.models.LocationField(map_attrs={})),
                ('address', mapbox_location_field.models.AddressAutoHiddenField(map_id='map')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='impresses.profile', verbose_name='Автор')),
            ],
        ),
    ]
