# Generated by Django 3.2 on 2021-04-25 09:20

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('impresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impress',
            name='address',
            field=mapbox_location_field.models.AddressAutoHiddenField(map_id='unique_id_1'),
        ),
        migrations.AlterField(
            model_name='impress',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': [92.87172071992194, 56.00781904796429], 'id': 'unique_id_1', 'marker_color': 'blue'}),
        ),
    ]
