# Generated by Django 3.1.7 on 2021-04-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresses', '0002_impress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='impress',
            name='avatar',
            field=models.CharField(max_length=255, null=True, verbose_name='Ссылка на аватар'),
        ),
        migrations.AlterField(
            model_name='impress',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
