# Generated by Django 3.1.7 on 2021-04-23 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('impresses', '0003_auto_20210423_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impress',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='impress',
            name='user',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=255, null=True, verbose_name='Ссылка на аватар')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='impress',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='impresses.profile', verbose_name='Автор'),
        ),
    ]
