# Generated by Django 3.1.7 on 2021-04-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresses', '0004_auto_20210423_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(max_length=255, verbose_name='Ссылка на аватар'),
        ),
    ]
